name: text-conversions
version: '0.3.0'
category: Data
synopsis: Safe conversions between textual types
description: Safe conversions between textual types
license: ISC
author: Alexis King
maintainer: lexi.lambda@gmail.com

github: cjdev/text-conversions

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE
- package.yaml
- stack.yaml

ghc-options: -Wall
default-extensions:
- FlexibleInstances
- MultiParamTypeClasses
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - bytestring <1
  - base16-bytestring <2
  - base64-bytestring <2
  - errors <3
  - text <2

tests:
  text-conversions-test-suite:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - text-conversions
    - bytestring
    - hspec
    - text
    verbatim: |
      build-tool-depends:
          hspec-discover:hspec-discover
